-- Template for creating bronze layer tables
CREATE OR REPLACE TABLE SNOWLAB_SANDBOX.BRONZE.{table_name} (
    -- Source data columns will go here
    -- Add your source data columns as needed
    
    -- Metadata columns
    LOAD_ID STRING DEFAULT SNOWLAB_SANDBOX.UTILS.GENERATE_UUID(),
    SOURCE_SYSTEM STRING,
    SOURCE_FILE_NAME STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT SNOWLAB_SANDBOX.UTILS.GET_CURRENT_TIMESTAMP(),
    ROW_HASH STRING,  -- For change detection
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    VALID_FROM TIMESTAMP_NTZ DEFAULT SNOWLAB_SANDBOX.UTILS.GET_CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ DEFAULT NULL
);

-- Create a stream for change data capture
CREATE OR REPLACE STREAM SNOWLAB_SANDBOX.BRONZE.{table_name}_STREAM ON TABLE SNOWLAB_SANDBOX.BRONZE.{table_name};

-- Create a task to maintain the current flag
CREATE OR REPLACE TASK SNOWLAB_SANDBOX.BRONZE.{table_name}_MAINTAIN_CURRENT
    WAREHOUSE = SNOWLAB_WH
    SCHEDULE = '1 MINUTE'
AS
    UPDATE SNOWLAB_SANDBOX.BRONZE.{table_name}
    SET IS_CURRENT = FALSE,
        VALID_TO = SNOWLAB_SANDBOX.UTILS.GET_CURRENT_TIMESTAMP()
    WHERE IS_CURRENT = TRUE
    AND ROW_HASH IN (
        SELECT ROW_HASH
        FROM SNOWLAB_SANDBOX.BRONZE.{table_name}_STREAM
        WHERE METADATA$ACTION = 'INSERT'
    ); 